"""add user fields to feedback_pairs

Revision ID: 09734f999302
Revises: 46ad7cf26243
Create Date: 2026-06-17 22:03:35.825427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '09734f999302'
down_revision: Union[str, Sequence[str], None] = '46ad7cf26243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_pairs', sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('feedback_pairs', sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback_pairs', 'user_email')
    op.drop_column('feedback_pairs', 'user_name')
    # ### end Alembic commands ###
