"""add resubmission lineage to review_submissions

Revision ID: 0a9bf882bd8b
Revises: 09734f999302
Create Date: 2026-06-30 19:45:48.795987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0a9bf882bd8b'
down_revision: Union[str, Sequence[str], None] = '09734f999302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_submissions', sa.Column('previous_submission_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('review_submissions', sa.Column('cycle', sa.Integer(), nullable=False, server_default='1'))
    op.create_index(op.f('ix_review_submissions_previous_submission_id'), 'review_submissions', ['previous_submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_submissions_previous_submission_id'), table_name='review_submissions')
    op.drop_column('review_submissions', 'cycle')
    op.drop_column('review_submissions', 'previous_submission_id')
    # ### end Alembic commands ###
